stages:
  - publish

publish-package:
  stage: publish
  image: node:10.15.3-alpine
  before_script:
    - echo //gitlab.sima-land.ru/api/v4/projects/919/packages/npm/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
    - npm version $CI_COMMIT_REF_NAME
  script:
    - npm publish
  only:
    refs:
      - tags
  tags:
    - sl-frontend
